import fs from "fs";
import path from "path";
import { Readable } from "stream";
import {
  S3Client,
  PutObjectCommand,
  DeleteObjectsCommand,
  GetObjectCommand,
  ListObjectVersionsCommand,
} from "@aws-sdk/client-s3";
import { env } from "../config/env";
import { logger } from "../utils/logger";

// Uploaded images live in S3 when S3_BUCKET is set, otherwise on local disk
// under env.uploadDir. Either way a stored image is addressed by a key like
// "properties/<32 hex chars>.jpg", and served at /api/uploads/<key>.

const s3 = env.s3.bucket ? new S3Client({ region: env.s3.region }) : null;

export const usingS3 = s3 !== null;

// Keys are always generated by us, but they also arrive from URLs in requests
// and the database — this keeps them to known folders and random filenames.
const KEY_PATTERN = /^(properties|blog|coming-soon)\/[a-f0-9]{32}\.(jpg|png|webp)$/;

export function isValidImageKey(key: string): boolean {
  return KEY_PATTERN.test(key);
}

const CONTENT_TYPES: Record<string, string> = { jpg: "image/jpeg", png: "image/png", webp: "image/webp" };

export async function saveImage(key: string, body: Buffer, contentType: string): Promise<void> {
  if (s3) {
    await s3.send(
      new PutObjectCommand({
        Bucket: env.s3.bucket!,
        Key: key,
        Body: body,
        ContentType: contentType,
        // Filenames are random, so the content behind a key never changes.
        CacheControl: "public, max-age=31536000, immutable",
      })
    );
    return;
  }

  const filePath = path.join(env.uploadDir, key);
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
  await fs.promises.writeFile(filePath, body);
}

export async function deleteImage(key: string): Promise<void> {
  if (!isValidImageKey(key)) return;
  try {
    if (s3) {
      await deleteAllVersions(s3, key);
    } else {
      await fs.promises.unlink(path.join(env.uploadDir, key));
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      logger.error(`Failed to delete image ${key}`, err);
    }
  }
}

/**
 * Removes a key completely. On a versioned bucket a plain DeleteObject only
 * adds a delete marker and keeps (and bills for) every old copy, so delete
 * each version and marker by id instead.
 */
async function deleteAllVersions(client: S3Client, key: string): Promise<void> {
  const bucket = env.s3.bucket!;
  const listed = await client.send(new ListObjectVersionsCommand({ Bucket: bucket, Prefix: key }));
  const versions = [...(listed.Versions ?? []), ...(listed.DeleteMarkers ?? [])]
    // Prefix matching could catch a longer key; only touch this exact one.
    .filter((v) => v.Key === key && v.VersionId)
    .map((v) => ({ Key: key, VersionId: v.VersionId! }));

  // Nothing stored under this key. (Unversioned buckets list their objects
  // with VersionId "null", so this also covers them.) A plain DeleteObject
  // here would only add an empty delete marker on a versioned bucket.
  if (versions.length === 0) return;

  const res = await client.send(new DeleteObjectsCommand({ Bucket: bucket, Delete: { Objects: versions, Quiet: true } }));
  if (res.Errors?.length) {
    throw new Error(`S3 refused to delete ${res.Errors.length} version(s) of ${key}: ${res.Errors[0].Code}`);
  }
}

/** Streams an image from S3; resolves null when the key doesn't exist. */
export async function readImageFromS3(
  key: string
): Promise<{ body: Readable; contentType: string; contentLength?: number } | null> {
  if (!s3 || !isValidImageKey(key)) return null;
  try {
    const res = await s3.send(new GetObjectCommand({ Bucket: env.s3.bucket!, Key: key }));
    return {
      body: res.Body as Readable,
      contentType: res.ContentType ?? CONTENT_TYPES[key.split(".").pop()!] ?? "application/octet-stream",
      contentLength: res.ContentLength,
    };
  } catch (err) {
    const name = (err as { name?: string }).name;
    if (name === "NoSuchKey" || name === "NotFound") return null;
    throw err;
  }
}
